# Generated by Django 5.2.14 on 2026-05-29 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_hashtag_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='user',
            new_name='name',
        ),
    ]
